name: Setup and cache
description: Setup for Node.js and pnpm

inputs:
  node-version:
    default: 20.x
    description: Node.js version for setup-node
    required: false

runs:
  using: composite

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Set Node.js version to ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: ${{ inputs.node-version }}
